/**
 * Billing: invoices, line items, payments and insurance claims.
 *
 * GET   /api/billing/invoices                 list
 * POST  /api/billing/invoices                 create (optionally from a visit)
 * GET   /api/billing/invoices/:id             invoice with items and payments
 * PATCH /api/billing/invoices/:id             edit a draft
 * POST  /api/billing/invoices/:id/items       add a charge
 * DELETE /api/billing/invoices/:id/items/:itemId
 * POST  /api/billing/invoices/:id/issue       draft -> issued
 * POST  /api/billing/invoices/:id/payments    record a payment
 * POST  /api/billing/invoices/:id/claim       submit / update an insurance claim
 * POST  /api/billing/invoices/:id/void        void an invoice
 * GET   /api/billing/summary                  revenue figures for the dashboard
 *
 * Totals are always recomputed from the line items rather than trusted from the
 * client, and the payment trigger in schema.sql keeps amount_paid/balance_due
 * correct no matter which client records the money.
 */
import { Router } from 'express';
import { one, rows, transaction } from '../db/pool.js';
import { asyncHandler, ok, created, paginated, readPagination, requireUuid } from '../lib/http.js';
import { notFound, badRequest } from '../lib/errors.js';
import { validate, z, text, money, listQuery } from '../lib/validate.js';
import { audit } from '../lib/audit.js';
import { requireAuth, requirePermission } from '../middleware/auth.js';

const router = Router();
router.use(requireAuth);

const INVOICE_SELECT = `
  SELECT i.*,
         pt.mrn, pt.first_name, pt.last_name,
         pt.first_name || ' ' || pt.last_name AS patient_name,
         v.visit_number,
         pi.policy_number, pi.provider_name AS insurance_provider,
         pi.verification_status AS insurance_status,
         creator.full_name AS created_by_name
    FROM invoices i
    JOIN patients pt ON pt.id = i.patient_id
    LEFT JOIN patient_visits v ON v.id = i.visit_id
    LEFT JOIN patient_insurance pi ON pi.id = i.patient_insurance_id
    LEFT JOIN staff creator ON creator.id = i.created_by
`;

/**
 * Recompute an invoice's money columns from its line items and insurance.
 * Runs inside the caller's transaction so an invoice is never briefly wrong.
 */
async function recalculateInvoice(client, invoiceId) {
  const { rows: totals } = await client.query(
    'SELECT COALESCE(sum(line_total), 0) AS subtotal FROM invoice_items WHERE invoice_id = $1',
    [invoiceId]
  );
  const subtotal = Number(totals[0].subtotal);

  const { rows: invoiceRows } = await client.query(
    `SELECT i.*, pi.coverage_percent, pi.copay_amount, pi.verification_status,
            ip.default_coverage, ip.default_copay
       FROM invoices i
       LEFT JOIN patient_insurance pi ON pi.id = i.patient_insurance_id
       LEFT JOIN insurance_providers ip ON ip.id = pi.provider_id
      WHERE i.id = $1`,
    [invoiceId]
  );
  const invoice = invoiceRows[0];

  const discount = Number(invoice.discount_amount ?? 0);
  const tax = Number(invoice.tax_amount ?? 0);
  const billable = Math.max(subtotal - discount, 0);

  let insuranceCovered = 0;
  let copay = 0;

  // Only a verified policy actually pays. Anything else bills the patient in
  // full, which is what a clinic would do while a claim is unconfirmed.
  if (invoice.billing_type !== 'self_pay' && invoice.verification_status === 'verified') {
    const coverage = Number(invoice.coverage_percent ?? invoice.default_coverage ?? 0);
    copay = Number(invoice.copay_amount ?? invoice.default_copay ?? 0);
    insuranceCovered = Math.min(billable * coverage, billable);
  }

  const total = Math.round((billable + tax) * 100) / 100;
  const patientResponsibility = Math.round(Math.max(total - insuranceCovered + copay, 0) * 100) / 100;

  const { rows: updated } = await client.query(
    `UPDATE invoices SET
       subtotal               = $2,
       insurance_covered      = $3,
       patient_responsibility = $4,
       total                  = $5,
       balance_due            = GREATEST($5 - amount_paid, 0)
     WHERE id = $1 RETURNING *`,
    [invoiceId, subtotal, Math.round(insuranceCovered * 100) / 100, patientResponsibility, total]
  );

  return updated[0];
}

/**
 * Gather every billable item generated by a visit: the consultation fee, each
 * dispensed medication, each completed lab and imaging order, and any surgery.
 */
async function collectVisitCharges(client, visitId) {
  const items = [];

  const { rows: settings } = await client.query(
    "SELECT key, value FROM clinic_settings WHERE key IN ('billing.visit_fee','billing.emergency_fee')"
  );
  const settingMap = Object.fromEntries(settings.map((s) => [s.key, Number(s.value)]));

  const { rows: visitRows } = await client.query(
    'SELECT visit_type, visit_number FROM patient_visits WHERE id = $1',
    [visitId]
  );
  if (visitRows.length === 0) throw notFound('Visit');
  const visit = visitRows[0];

  const visitFee =
    visit.visit_type === 'emergency'
      ? settingMap['billing.emergency_fee'] ?? 500
      : settingMap['billing.visit_fee'] ?? 150;

  items.push({
    item_type: 'visit',
    source_id: visitId,
    description: `${visit.visit_type.replace('_', ' ')} consultation (${visit.visit_number})`,
    quantity: 1,
    unit_price: visitFee,
  });

  const { rows: meds } = await client.query(
    `SELECT rx.id, rx.medication_name, rx.quantity, COALESCE(m.unit_cost, 0) AS unit_cost
       FROM prescriptions rx
       LEFT JOIN medications m ON m.id = rx.medication_id
       LEFT JOIN pharmacy_queue pq ON pq.prescription_id = rx.id
      WHERE rx.visit_id = $1 AND rx.deleted_at IS NULL
        AND (pq.status IN ('picked_up','ready') OR rx.status IN ('dispensed','filled'))`,
    [visitId]
  );
  for (const med of meds) {
    if (Number(med.unit_cost) <= 0) continue;
    items.push({
      item_type: 'medication',
      source_id: med.id,
      description: med.medication_name,
      quantity: med.quantity,
      unit_price: Number(med.unit_cost),
    });
  }

  const { rows: labs } = await client.query(
    `SELECT lo.id, lo.test_name, COALESCE(cat.cost, 0) AS cost
       FROM laboratory_orders lo
       LEFT JOIN lab_test_catalog cat ON cat.id = lo.test_id
      WHERE lo.visit_id = $1 AND lo.deleted_at IS NULL AND lo.status = 'completed'`,
    [visitId]
  );
  for (const lab of labs) {
    if (Number(lab.cost) <= 0) continue;
    items.push({
      item_type: 'laboratory',
      source_id: lab.id,
      description: `Laboratory: ${lab.test_name}`,
      quantity: 1,
      unit_price: Number(lab.cost),
    });
  }

  const { rows: imaging } = await client.query(
    `SELECT ro.id, ro.study_name, ro.modality, COALESCE(cat.cost, 0) AS cost
       FROM radiology_orders ro
       LEFT JOIN lab_test_catalog cat ON cat.id = ro.test_id
      WHERE ro.visit_id = $1 AND ro.deleted_at IS NULL AND ro.status = 'completed'`,
    [visitId]
  );
  for (const study of imaging) {
    if (Number(study.cost) <= 0) continue;
    items.push({
      item_type: 'radiology',
      source_id: study.id,
      description: `${study.modality.toUpperCase()}: ${study.study_name}`,
      quantity: 1,
      unit_price: Number(study.cost),
    });
  }

  const { rows: surgeries } = await client.query(
    `SELECT id, procedure_name, cost FROM surgeries
      WHERE visit_id = $1 AND deleted_at IS NULL AND status = 'completed' AND cost > 0`,
    [visitId]
  );
  for (const surgery of surgeries) {
    items.push({
      item_type: 'surgery',
      source_id: surgery.id,
      description: `Surgery: ${surgery.procedure_name}`,
      quantity: 1,
      unit_price: Number(surgery.cost),
    });
  }

  return items;
}

// --- Invoices --------------------------------------------------------------

router.get(
  '/invoices',
  requirePermission('billing:read'),
  validate(
    listQuery.extend({
      status: z.string().max(20).optional(),
      patient_id: z.string().uuid().optional(),
      visit_id: z.string().uuid().optional(),
    }),
    'query'
  ),
  asyncHandler(async (req, res) => {
    const { page, limit, offset } = readPagination(req);
    const q = req.validatedQuery;

    const filters = ['i.deleted_at IS NULL'];
    const params = [];
    const add = (value, build) => {
      params.push(value);
      filters.push(build(`$${params.length}`));
    };

    if (q.status) add(q.status, (p) => `i.status = ${p}`);
    if (q.patient_id) add(q.patient_id, (p) => `i.patient_id = ${p}`);
    if (q.visit_id) add(q.visit_id, (p) => `i.visit_id = ${p}`);
    if (q.search) {
      add(`%${q.search}%`, (p) => `(i.invoice_number ILIKE ${p} OR (pt.first_name || ' ' || pt.last_name) ILIKE ${p} OR pt.mrn ILIKE ${p})`);
    }

    const where = filters.join(' AND ');

    const { count } = await one(
      `SELECT count(*)::int AS count FROM invoices i JOIN patients pt ON pt.id = i.patient_id WHERE ${where}`,
      params
    );

    const list = await rows(
      `${INVOICE_SELECT} WHERE ${where} ORDER BY i.created_at DESC
        LIMIT $${params.length + 1} OFFSET $${params.length + 2}`,
      [...params, limit, offset]
    );

    return paginated(res, list, { page, limit, total: count });
  })
);

router.post(
  '/invoices',
  requirePermission('billing:write'),
  validate(
    z.object({
      patient_id: z.string().uuid(),
      visit_id: z.string().uuid().optional().nullable(),
      billing_type: z.enum(['self_pay', 'insurance', 'mixed', 'waived']).default('self_pay'),
      patient_insurance_id: z.string().uuid().optional().nullable(),
      discount_amount: money.default(0),
      tax_amount: money.default(0),
      due_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
      /** Pull every billable item from the visit automatically. */
      auto_charges: z.boolean().default(true),
      items: z
        .array(
          z.object({
            item_type: z.enum(['visit', 'medication', 'laboratory', 'radiology', 'surgery', 'procedure', 'supply', 'other']),
            description: text(300, 'Description'),
            quantity: z.coerce.number().min(0.01).max(10_000).default(1),
            unit_price: money,
          })
        )
        .max(100)
        .optional(),
    })
  ),
  asyncHandler(async (req, res) => {
    const b = req.body;

    const patient = await one(
      'SELECT id, first_name, last_name FROM patients WHERE id = $1 AND deleted_at IS NULL',
      [b.patient_id]
    );
    if (!patient) throw notFound('Patient');

    const invoice = await transaction(async (client) => {
      // Default to the patient's primary policy when billing insurance.
      let insuranceId = b.patient_insurance_id ?? null;
      if (!insuranceId && b.billing_type !== 'self_pay') {
        const { rows: policy } = await client.query(
          `SELECT id FROM patient_insurance
            WHERE patient_id = $1 AND deleted_at IS NULL
            ORDER BY is_primary DESC, created_at DESC LIMIT 1`,
          [b.patient_id]
        );
        insuranceId = policy[0]?.id ?? null;
      }

      const { rows: inserted } = await client.query(
        `INSERT INTO invoices
           (patient_id, visit_id, billing_type, patient_insurance_id,
            discount_amount, tax_amount, due_date, created_by, claim_status)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,
        [
          b.patient_id, b.visit_id ?? null, b.billing_type, insuranceId,
          b.discount_amount, b.tax_amount, b.due_date ?? null, req.staff.id,
          b.billing_type === 'self_pay' ? null : 'not_submitted',
        ]
      );
      const record = inserted[0];

      const lineItems = [...(b.items ?? [])];
      if (b.auto_charges && b.visit_id) {
        lineItems.push(...(await collectVisitCharges(client, b.visit_id)));
      }

      for (const item of lineItems) {
        const lineTotal = Math.round(Number(item.quantity) * Number(item.unit_price) * 100) / 100;
        await client.query(
          `INSERT INTO invoice_items (invoice_id, item_type, source_id, description, quantity, unit_price, line_total)
           VALUES ($1,$2,$3,$4,$5,$6,$7)`,
          [record.id, item.item_type, item.source_id ?? null, item.description, item.quantity, item.unit_price, lineTotal]
        );
      }

      return recalculateInvoice(client, record.id);
    });

    await audit({
      req, action: 'create', entityType: 'invoices', entityId: invoice.id,
      description: `Created invoice ${invoice.invoice_number} for ${patient.first_name} ${patient.last_name} (${invoice.total})`,
    });

    return created(res, invoice);
  })
);

router.get(
  '/invoices/:id',
  requirePermission('billing:read'),
  asyncHandler(async (req, res) => {
    const id = requireUuid(req.params.id, 'invoice id');

    const invoice = await one(`${INVOICE_SELECT} WHERE i.id = $1 AND i.deleted_at IS NULL`, [id]);
    if (!invoice) throw notFound('Invoice');

    const [items, paymentList] = await Promise.all([
      rows('SELECT * FROM invoice_items WHERE invoice_id = $1 ORDER BY item_type, created_at', [id]),
      rows(
        `SELECT p.*, s.full_name AS received_by_name
           FROM payments p LEFT JOIN staff s ON s.id = p.received_by
          WHERE p.invoice_id = $1 ORDER BY p.paid_at DESC`,
        [id]
      ),
    ]);

    return ok(res, { ...invoice, items, payments: paymentList });
  })
);

router.patch(
  '/invoices/:id',
  requirePermission('billing:write'),
  validate(
    z.object({
      billing_type: z.enum(['self_pay', 'insurance', 'mixed', 'waived']).optional(),
      patient_insurance_id: z.string().uuid().optional().nullable(),
      discount_amount: money.optional(),
      tax_amount: money.optional(),
      due_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().nullable(),
    })
  ),
  asyncHandler(async (req, res) => {
    const id = requireUuid(req.params.id, 'invoice id');
    const existing = await one('SELECT * FROM invoices WHERE id = $1 AND deleted_at IS NULL', [id]);
    if (!existing) throw notFound('Invoice');
    if (['paid', 'void', 'written_off'].includes(existing.status)) {
      throw badRequest(`A ${existing.status} invoice cannot be edited.`);
    }

    const b = req.body;
    const updated = await transaction(async (client) => {
      await client.query(
        `UPDATE invoices SET
           billing_type         = COALESCE($2, billing_type),
           patient_insurance_id = COALESCE($3, patient_insurance_id),
           discount_amount      = COALESCE($4, discount_amount),
           tax_amount           = COALESCE($5, tax_amount),
           due_date             = COALESCE($6, due_date)
         WHERE id = $1`,
        [id, b.billing_type ?? null, b.patient_insurance_id ?? null, b.discount_amount ?? null, b.tax_amount ?? null, b.due_date ?? null]
      );
      return recalculateInvoice(client, id);
    });

    await audit({ req, action: 'update', entityType: 'invoices', entityId: id, description: `Updated invoice ${existing.invoice_number}` });
    return ok(res, updated);
  })
);

router.post(
  '/invoices/:id/items',
  requirePermission('billing:write'),
  validate(
    z.object({
      item_type: z.enum(['visit', 'medication', 'laboratory', 'radiology', 'surgery', 'procedure', 'supply', 'other']),
      description: text(300, 'Description'),
      quantity: z.coerce.number().min(0.01).max(10_000).default(1),
      unit_price: money,
    })
  ),
  asyncHandler(async (req, res) => {
    const id = requireUuid(req.params.id, 'invoice id');
    const invoice = await one('SELECT * FROM invoices WHERE id = $1 AND deleted_at IS NULL', [id]);
    if (!invoice) throw notFound('Invoice');
    if (['paid', 'void', 'written_off'].includes(invoice.status)) {
      throw badRequest(`A ${invoice.status} invoice cannot be changed.`);
    }

    const b = req.body;
    const lineTotal = Math.round(b.quantity * b.unit_price * 100) / 100;

    const result = await transaction(async (client) => {
      const { rows: item } = await client.query(
        `INSERT INTO invoice_items (invoice_id, item_type, description, quantity, unit_price, line_total)
         VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`,
        [id, b.item_type, b.description, b.quantity, b.unit_price, lineTotal]
      );
      const refreshed = await recalculateInvoice(client, id);
      return { item: item[0], invoice: refreshed };
    });

    await audit({
      req, action: 'create', entityType: 'invoice_items', entityId: result.item.id,
      description: `Added "${b.description}" (${lineTotal}) to ${invoice.invoice_number}`,
    });

    return created(res, result);
  })
);

router.delete(
  '/invoices/:id/items/:itemId',
  requirePermission('billing:write'),
  asyncHandler(async (req, res) => {
    const id = requireUuid(req.params.id, 'invoice id');
    const itemId = requireUuid(req.params.itemId, 'item id');

    const result = await transaction(async (client) => {
      const { rows: removed } = await client.query(
        'DELETE FROM invoice_items WHERE id = $1 AND invoice_id = $2 RETURNING description',
        [itemId, id]
      );
      if (removed.length === 0) return null;
      const refreshed = await recalculateInvoice(client, id);
      return { removed: removed[0], invoice: refreshed };
    });

    if (!result) throw notFound('Invoice item');

    await audit({ req, action: 'delete', entityType: 'invoice_items', entityId: itemId, description: `Removed "${result.removed.description}"` });
    return ok(res, result.invoice);
  })
);

router.post(
  '/invoices/:id/issue',
  requirePermission('billing:write'),
  asyncHandler(async (req, res) => {
    const id = requireUuid(req.params.id, 'invoice id');

    const issued = await one(
      `UPDATE invoices
          SET status = 'issued', issued_at = COALESCE(issued_at, now()),
              due_date = COALESCE(due_date, (now() + interval '30 days')::date)
        WHERE id = $1 AND deleted_at IS NULL AND status = 'draft'
        RETURNING *`,
      [id]
    );
    if (!issued) throw badRequest('Only a draft invoice can be issued.');

    await audit({ req, action: 'issue', entityType: 'invoices', entityId: id, description: `Issued invoice ${issued.invoice_number}` });
    return ok(res, issued);
  })
);

router.post(
  '/invoices/:id/payments',
  requirePermission('billing:write'),
  validate(
    z.object({
      amount: money.refine((v) => v > 0, 'Amount must be greater than zero'),
      method: z.enum(['cash', 'card', 'linden', 'insurance', 'bank_transfer', 'waived', 'other']).default('cash'),
      reference: z.string().max(120).optional().nullable(),
      notes: z.string().max(1000).optional().nullable(),
    })
  ),
  asyncHandler(async (req, res) => {
    const id = requireUuid(req.params.id, 'invoice id');
    const b = req.body;

    const invoice = await one('SELECT * FROM invoices WHERE id = $1 AND deleted_at IS NULL', [id]);
    if (!invoice) throw notFound('Invoice');
    if (['void', 'written_off'].includes(invoice.status)) throw badRequest(`A ${invoice.status} invoice cannot take payments.`);
    if (invoice.status === 'draft') throw badRequest('Issue the invoice before recording a payment.');

    // Overpayment is almost always a typo; refuse rather than silently
    // producing a negative balance.
    if (b.amount > Number(invoice.balance_due) + 0.001) {
      throw badRequest(`That is more than the outstanding balance of ${invoice.balance_due}.`);
    }

    const payment = await one(
      `INSERT INTO payments (invoice_id, patient_id, amount, method, reference, notes, received_by)
       VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *`,
      [id, invoice.patient_id, b.amount, b.method, b.reference ?? null, b.notes ?? null, req.staff.id]
    );

    // The AFTER trigger on payments has already updated the invoice.
    const refreshed = await one('SELECT * FROM invoices WHERE id = $1', [id]);

    await audit({
      req, action: 'payment', entityType: 'invoices', entityId: id,
      description: `Recorded ${b.amount} (${b.method}) against ${invoice.invoice_number}; balance now ${refreshed.balance_due}`,
    });

    return created(res, { payment, invoice: refreshed });
  })
);

router.post(
  '/invoices/:id/claim',
  requirePermission('billing:write'),
  validate(
    z.object({
      claim_status: z.enum(['submitted', 'approved', 'denied', 'partially_approved']).default('submitted'),
      claim_reference: z.string().max(120).optional().nullable(),
      claim_notes: z.string().max(2000).optional().nullable(),
      /** Amount the insurer agreed to pay, for approved/partial outcomes. */
      approved_amount: money.optional(),
    })
  ),
  asyncHandler(async (req, res) => {
    const id = requireUuid(req.params.id, 'invoice id');
    const b = req.body;

    const invoice = await one('SELECT * FROM invoices WHERE id = $1 AND deleted_at IS NULL', [id]);
    if (!invoice) throw notFound('Invoice');
    if (invoice.billing_type === 'self_pay') throw badRequest('This is a self-pay invoice; there is nothing to claim.');
    if (!invoice.patient_insurance_id) throw badRequest('No insurance policy is attached to this invoice.');

    const updated = await transaction(async (client) => {
      await client.query(
        `UPDATE invoices SET
           claim_status       = $2,
           claim_reference    = COALESCE($3, claim_reference),
           claim_notes        = COALESCE($4, claim_notes),
           claim_submitted_at = COALESCE(claim_submitted_at, now())
         WHERE id = $1`,
        [id, b.claim_status, b.claim_reference ?? null, b.claim_notes ?? null]
      );

      // An approved claim pays out; record it as a payment so the ledger and
      // the balance both reflect reality.
      if (['approved', 'partially_approved'].includes(b.claim_status)) {
        const amount = b.approved_amount ?? Number(invoice.insurance_covered);
        if (amount > 0) {
          const { rows: already } = await client.query(
            "SELECT 1 FROM payments WHERE invoice_id = $1 AND method = 'insurance' LIMIT 1",
            [id]
          );
          if (already.length === 0) {
            await client.query(
              `INSERT INTO payments (invoice_id, patient_id, amount, method, reference, notes, received_by)
               VALUES ($1,$2,$3,'insurance',$4,'Insurance claim settlement',$5)`,
              [id, invoice.patient_id, Math.min(amount, Number(invoice.balance_due)), b.claim_reference ?? null, req.staff.id]
            );
          }
        }
      }

      const { rows: r } = await client.query('SELECT * FROM invoices WHERE id = $1', [id]);
      return r[0];
    });

    await audit({
      req, action: 'claim', entityType: 'invoices', entityId: id,
      description: `Insurance claim ${b.claim_status} for ${invoice.invoice_number}`,
    });

    return ok(res, updated);
  })
);

router.post(
  '/invoices/:id/void',
  requirePermission('billing:write'),
  validate(z.object({ reason: text(500, 'Reason') })),
  asyncHandler(async (req, res) => {
    const id = requireUuid(req.params.id, 'invoice id');

    const voided = await one(
      `UPDATE invoices
          SET status = 'void', claim_notes = COALESCE(claim_notes || E'\\n', '') || 'Voided: ' || $2
        WHERE id = $1 AND deleted_at IS NULL AND amount_paid = 0 AND status <> 'void'
        RETURNING *`,
      [id, req.body.reason]
    );
    if (!voided) throw badRequest('Only an unpaid, non-void invoice can be voided.');

    await audit({ req, action: 'void', entityType: 'invoices', entityId: id, description: `Voided ${voided.invoice_number}: ${req.body.reason}` });
    return ok(res, voided);
  })
);

// --- Reporting -------------------------------------------------------------

router.get(
  '/summary',
  requirePermission('billing:read'),
  validate(z.object({ days: z.coerce.number().int().min(1).max(365).optional() }), 'query'),
  asyncHandler(async (req, res) => {
    const days = req.validatedQuery.days ?? 30;

    const [today, period, outstanding, byMethod] = await Promise.all([
      one(
        `SELECT COALESCE(sum(amount), 0) AS revenue, count(*)::int AS payments
           FROM payments WHERE paid_at::date = CURRENT_DATE`
      ),
      one(
        `SELECT COALESCE(sum(amount), 0) AS revenue, count(*)::int AS payments
           FROM payments WHERE paid_at >= now() - ($1 || ' days')::interval`,
        [String(days)]
      ),
      one(
        `SELECT COALESCE(sum(balance_due), 0) AS outstanding,
                count(*) FILTER (WHERE status IN ('issued','partially_paid'))::int AS open_invoices,
                count(*) FILTER (WHERE status = 'overdue' OR (due_date < CURRENT_DATE AND balance_due > 0))::int AS overdue
           FROM invoices WHERE deleted_at IS NULL AND status NOT IN ('void','written_off','draft')`
      ),
      rows(
        `SELECT method, COALESCE(sum(amount), 0) AS total, count(*)::int AS count
           FROM payments WHERE paid_at >= now() - ($1 || ' days')::interval
          GROUP BY method ORDER BY total DESC`,
        [String(days)]
      ),
    ]);

    const daily = await rows(
      `SELECT paid_at::date AS date, COALESCE(sum(amount), 0) AS revenue
         FROM payments WHERE paid_at >= now() - ($1 || ' days')::interval
        GROUP BY paid_at::date ORDER BY date`,
      [String(days)]
    );

    return ok(res, { today, period: { ...period, days }, outstanding, by_method: byMethod, daily });
  })
);

export default router;
